// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/tax-rates": {
    params: {};
  };
  "/tax-rates/:code": {
    params: {
      "code": string;
    };
  };
  "/company": {
    params: {};
  };
  "/tools/evaluate": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/tax-rates" | "/tax-rates/:code" | "/company" | "/tools/evaluate" | "/settings";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/tax-rates.tsx": {
    id: "routes/tax-rates";
    page: "/tax-rates";
  };
  "routes/tax-rates.$code.tsx": {
    id: "routes/tax-rates.$code";
    page: "/tax-rates/:code";
  };
  "routes/company.tsx": {
    id: "routes/company";
    page: "/company";
  };
  "routes/tools.evaluate.tsx": {
    id: "routes/tools.evaluate";
    page: "/tools/evaluate";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};