// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/connections": {
    params: {};
  };
  "/connections/new": {
    params: {};
  };
  "/tax-rates": {
    params: {};
  };
  "/tax-rates/:code": {
    params: {
      "code": string;
    };
  };
  "/company": {
    params: {};
  };
  "/groups": {
    params: {};
  };
  "/tools/evaluate": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/test-routes": {
    params: {};
  };
  "/test-auth": {
    params: {};
  };
  "/test-create-connection": {
    params: {};
  };
  "/api/connections": {
    params: {};
  };
  "/api/debug/connections": {
    params: {};
  };
  "/api/groups": {
    params: {};
  };
  "/api/groups/members": {
    params: {};
  };
  "/api/moneyworks": {
    params: {};
  };
  "/api/moneyworks-test": {
    params: {};
  };
  "/debug-auth": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/welcome" | "/sign-in" | "/sign-up" | "/dashboard" | "/onboarding" | "/connections" | "/connections/new" | "/tax-rates" | "/tax-rates/:code" | "/company" | "/groups" | "/tools/evaluate" | "/settings" | "/test-routes" | "/test-auth" | "/test-create-connection" | "/api/connections" | "/api/debug/connections" | "/api/groups" | "/api/groups/members" | "/api/moneyworks" | "/api/moneyworks-test" | "/debug-auth";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/welcome.tsx": {
    id: "routes/welcome";
    page: "/welcome";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/sign-up.tsx": {
    id: "routes/sign-up";
    page: "/sign-up";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/connections/index.tsx": {
    id: "routes/connections/index";
    page: "/connections";
  };
  "routes/connections/new.tsx": {
    id: "routes/connections/new";
    page: "/connections/new";
  };
  "routes/tax-rates.tsx": {
    id: "routes/tax-rates";
    page: "/tax-rates";
  };
  "routes/tax-rates.$code.tsx": {
    id: "routes/tax-rates.$code";
    page: "/tax-rates/:code";
  };
  "routes/company.tsx": {
    id: "routes/company";
    page: "/company";
  };
  "routes/groups.tsx": {
    id: "routes/groups";
    page: "/groups";
  };
  "routes/tools.evaluate.tsx": {
    id: "routes/tools.evaluate";
    page: "/tools/evaluate";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/test-routes.tsx": {
    id: "routes/test-routes";
    page: "/test-routes";
  };
  "routes/test-auth.tsx": {
    id: "routes/test-auth";
    page: "/test-auth";
  };
  "routes/test-create-connection.tsx": {
    id: "routes/test-create-connection";
    page: "/test-create-connection";
  };
  "routes/api.connections.tsx": {
    id: "routes/api.connections";
    page: "/api/connections";
  };
  "routes/api.debug.connections.tsx": {
    id: "routes/api.debug.connections";
    page: "/api/debug/connections";
  };
  "routes/api.groups.tsx": {
    id: "routes/api.groups";
    page: "/api/groups";
  };
  "routes/api.groups.members.tsx": {
    id: "routes/api.groups.members";
    page: "/api/groups/members";
  };
  "routes/api.moneyworks.tsx": {
    id: "routes/api.moneyworks";
    page: "/api/moneyworks";
  };
  "routes/api.moneyworks-test.tsx": {
    id: "routes/api.moneyworks-test";
    page: "/api/moneyworks-test";
  };
  "routes/debug-auth.tsx": {
    id: "routes/debug-auth";
    page: "/debug-auth";
  };
};