import { t } from 'elysia';
export const JobSheetOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.Date(),
  Job: t.String(),
  Qty: t.Optional(t.Number()),
  Resource: t.Optional(t.String()),
  Date: t.Date(),
  CostCentre: t.Optional(t.String()),
  Account: t.Optional(t.String()),
  Period: t.Optional(t.Number()),
  Units: t.Optional(t.String()),
  CostPrice: t.Optional(t.Number()),
  SellPrice: t.Optional(t.Number()),
  Memo: t.Optional(t.String()),
  DestTransSeq: t.Optional(t.Number()),
  SourceTransSeq: t.Optional(t.Number()),
  DateEntered: t.Optional(t.Date()),
  Flags: t.Optional(t.Number()),
  Colour: t.Optional(t.Number()),
  Status: t.Optional(t.String()),
  Type: t.Optional(t.String()),
  Analysis: t.Optional(t.String()),
  BillValue: t.Optional(t.Number()),
  ActivityCode: t.Optional(t.String()),
  Comments: t.Optional(t.String()),
  Batch: t.Optional(t.Number()),
  EnteredBy: t.Optional(t.String()),
  SerialNumber: t.Optional(t.String()),
  StockLocation: t.Optional(t.String()),
  UserNum: t.Optional(t.Number()),
  UserText: t.Optional(t.String()),
  TaggedText: t.Optional(t.String()),
  TimeProcessed: t.Optional(t.Date()),
});
export const JobSheetMany = t.Object({
  data: t.Array(JobSheetOne),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  })
});
