/**
 * MoneyWorks Contact Type Definitions
 *
 * @moneyworks-entity Contact
 * @moneyworks-table Contact
 * @moneyworks-dsl PURE
 *
 * @ai-instruction USE ONLY MoneyWorks field names. NEVER translate to generic business terms.
 * @ai-forbidden person, employee, staff, individual
 * @ai-required Contact, ParentSeq, Role, eMail, DDI, Mobile
 *
 * Contacts are a subfile of Names, providing unlimited additional contacts
 * beyond the built-in Contact1/Contact2 fields in the Names table.
 */

/**
 * MoneyWorks Contact Entity
 *
 * CRITICAL: Contacts link to Names via ParentSeq (Name.SequenceNumber).
 * Use the Role bitmask field to tag contacts for specific functions.
 *
 * @ai-critical NEVER translate MoneyWorks field names (ParentSeq, eMail, DDI)
 * @ai-context Contact records cannot exist without a parent Name record
 */
export interface MoneyWorksContact {
	/**
	 * Sequence number of the parent Name record
	 * @moneyworks-field ParentSeq
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "ParentSeq", NEVER "parentId", "nameId", or "customerId"
	 * @ai-context References Names.SequenceNumber - required field
	 */
	ParentSeq: number;

	/**
	 * Unique sequence number for this contact record
	 * @moneyworks-field SequenceNumber
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "SequenceNumber", NEVER "id" or "contactId"
	 * @ai-context Auto-generated by MoneyWorks
	 */
	SequenceNumber?: number;

	/**
	 * Sort order within the parent Name record
	 * @moneyworks-field Order
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "Order", NEVER "sortOrder" or "position"
	 * @ai-context Determines display order in contact lists
	 */
	Order?: number;

	/**
	 * Bit-mapped role flags
	 * @moneyworks-field Role
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "Role", NEVER "roleType" or "function"
	 * @ai-context 16-bit field, use bitwise operations to check roles
	 * @example Role = 5 means bits 1 and 3 are set (Payables + Technical)
	 */
	Role?: number;

	// PERSONAL DETAILS

	/**
	 * Full name of the contact
	 * @moneyworks-field Contact
	 * @moneyworks-type T(39)
	 * @ai-term ALWAYS use "Contact", NEVER "name", "fullName", or "personName"
	 * @ai-context 39 chars max (more than Names.Contact at 25/29)
	 */
	Contact?: string;

	/**
	 * Formal greeting
	 * @moneyworks-field Salutation
	 * @moneyworks-type T(39)
	 * @ai-term ALWAYS use "Salutation", NEVER "greeting" or "title"
	 * @example "Mr Smith", "Dr Jones"
	 */
	Salutation?: string;

	/**
	 * Job title
	 * @moneyworks-field Position
	 * @moneyworks-type T(39)
	 * @ai-term ALWAYS use "Position", NEVER "jobTitle" or "role"
	 * @ai-context 39 chars (more than Names.Position at 29)
	 */
	Position?: string;

	/**
	 * Internal notes
	 * @moneyworks-field Memo
	 * @moneyworks-type T(255)
	 * @ai-term ALWAYS use "Memo", NEVER "notes" or "comments"
	 */
	Memo?: string;

	// COMMUNICATION FIELDS

	/**
	 * Email address
	 * @moneyworks-field eMail
	 * @moneyworks-type T(63)
	 * @ai-term ALWAYS use "eMail" (with lowercase 'e'), NEVER "email" or "emailAddress"
	 * @ai-critical 63 chars max - SHORTER than Names.email (80 chars)!
	 * @ai-context Be careful when migrating from Names.email to Contact.eMail
	 */
	eMail?: string;

	/**
	 * Mobile phone number
	 * @moneyworks-field Mobile
	 * @moneyworks-type T(19)
	 * @ai-term ALWAYS use "Mobile", NEVER "cell" or "mobilePhone"
	 * @ai-context 19 chars (more than Names.mobile at 14)
	 */
	Mobile?: string;

	/**
	 * Direct dial phone number
	 * @moneyworks-field DDI
	 * @moneyworks-type T(19)
	 * @ai-term ALWAYS use "DDI", NEVER "directLine" or "extension"
	 * @ai-context Direct Dial In - personal phone line
	 */
	DDI?: string;

	/**
	 * After hours phone number
	 * @moneyworks-field AfterHours
	 * @moneyworks-type T(19)
	 * @ai-term ALWAYS use "AfterHours", NEVER "homePhone" or "emergency"
	 */
	AfterHours?: string;

	// SYSTEM FIELDS

	/**
	 * Date and time record was last modified
	 * @moneyworks-field LastModifiedTime
	 * @moneyworks-type S
	 * @ai-context Read-only, set by MoneyWorks
	 */
	LastModifiedTime?: string;

	/**
	 * Record colour indicator
	 * @moneyworks-field Colour
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "Colour" (British spelling), NEVER "color"
	 * @ai-context Numeric index 0-7
	 */
	Colour?: number;

	// USER-DEFINED FIELDS

	/**
	 * Scriptable number storage
	 * @moneyworks-field UserNum
	 * @moneyworks-type N
	 * @ai-context Available for custom calculations/scripts
	 */
	UserNum?: number;

	/**
	 * Scriptable text storage
	 * @moneyworks-field UserText
	 * @moneyworks-type T(255)
	 * @ai-context Available for custom text data
	 */
	UserText?: string;

	/**
	 * Scriptable tag storage
	 * @moneyworks-field TaggedText
	 * @moneyworks-type T(255)
	 * @ai-context Available for custom tag-based data
	 */
	TaggedText?: string;
}

/**
 * MoneyWorks Contact creation input
 * Required fields for creating a new contact
 *
 * @ai-instruction You CANNOT create a Contact without a parent Name record
 * @ai-critical ParentSeq is REQUIRED - must be a valid Names.SequenceNumber
 */
export interface MoneyWorksContactCreateInput {
	/**
	 * Required: Parent Name record sequence number
	 * @ai-critical Must be a valid Names.SequenceNumber
	 */
	ParentSeq: number;

	/**
	 * Contact name - typically the person's full name
	 */
	Contact?: string;

	/**
	 * Email address (max 63 chars)
	 */
	eMail?: string;

	/**
	 * Role bitmask (optional, defaults to 0)
	 */
	Role?: number;

	/**
	 * Sort order within parent (optional)
	 */
	Order?: number;
}

/**
 * MoneyWorks Contact update input
 * All fields optional - only changed fields need to be included
 *
 * @ai-instruction When updating contacts, include only fields being changed
 */
export interface MoneyWorksContactUpdateInput {
	// Personal details
	Contact?: string;
	Salutation?: string;
	Position?: string;
	Memo?: string;

	// Communication
	eMail?: string;
	Mobile?: string;
	DDI?: string;
	AfterHours?: string;

	// Role and order
	Role?: number;
	Order?: number;

	// Metadata
	Colour?: number;

	// User-defined
	UserNum?: number;
	UserText?: string;
	TaggedText?: string;
}

/**
 * MoneyWorks Contact filter for search/query operations
 *
 * @ai-instruction When searching contacts, use this interface
 */
export interface MoneyWorksContactFilter {
	/**
	 * Filter by parent Name sequence number
	 * @ai-instruction Use to find all contacts for a specific Name
	 */
	parentSeq?: number;

	/**
	 * Filter by parent Name code
	 * @ai-context Requires lookup of Name.SequenceNumber first
	 */
	nameCode?: string;

	/**
	 * Filter by role bit(s)
	 * @ai-instruction Use bitwise check: (Role & roleBit) !== 0
	 */
	roleBit?: number;

	/**
	 * Search by email address
	 * @ai-instruction Case-insensitive search
	 */
	email?: string;

	/**
	 * Search text (searches Contact, Position, Memo)
	 */
	searchText?: string;
}

/**
 * Contact field capacity comparison with Names table
 * For developer reference when deciding which contact storage to use
 */
export const CONTACT_VS_NAMES_CAPACITY = {
	Contact: { contact: 39, names: "25/29" },
	Position: { contact: 39, names: 29 },
	Mobile: { contact: 19, names: 14 },
	eMail: { contact: 63, names: 80 }, // NOTE: Contact has LESS capacity!
} as const;

/**
 * Type for Contact field capacity info
 */
export type ContactCapacityField = keyof typeof CONTACT_VS_NAMES_CAPACITY;
