import type { AccountField } from "../../interface/tables/account";

export default {
  SequenceNumber: "integer",
  LastModifiedTime: "string",
  Code: "string",
  Type: "string",
  Group: "string",
  Category: "string",
  Description: "string",
  PandL: "string",
  TaxCode: "string",
  Flags: "integer",
  System: "string",
  Created: "string",
  Category2: "string",
  Category3: "string",
  Category4: "string",
  AccountantCode: "string",
  Colour: "integer",
  Currency: "string",
  SecurityLevel: "integer",
  BankAccountNumber: "string",
  BalanceLimit: "number",
  ManualChequeNumber: "string",
  PrintedChequeNumber: "string",
  LastStatementImport: "string",
  Comments: "string",
  ManualChequeNumDigits: "integer",
  PrintedChequeNumDigits: "integer",
  UserNum: "number",
  UserText: "string",
  TaggedText: "string",
  FeedID: "string",
  Cashflow: "string",
  Cashforecast: "string",
  EBITDA: "string",
  ImportFormat: "string",
} as Record<AccountField, string>;
