export default {
  SequenceNumber: "number",
  LastModifiedTime: "string",
  Code: "string",
  Description: "string",
  AssetAccount: "string",
  DepExpense: "string",
  AccumDep: "string",
  GainLoss: "string",
  Custom: "string",
  Group: "string",
  Type: "string",
  Impairment: "string",
  Rate: "number",
  RevalSurplus: "string",
  GainLossPrivate: "string",
  DepExpensePrivate: "string",
  UserNum: "number",
  UserText: "string",
  LastDepreciatedDate: "string",
  TaggedText: "string",
  Flags: "number",
};
