import { t } from "elysia";

export const DetailOne = t.Object(
  {
    SequenceNumber: t.Nullable(t.Integer()),
    LastModifiedTime: t.Nullable(t.String()),
    ParentSeq: t.Nullable(t.Integer()),
    Sort: t.Nullable(t.Integer()),
    Account: t.Nullable(t.String()),
    Dept: t.Nullable(t.String()),
    PostedQty: t.Nullable(t.Integer()),
    TaxCode: t.Nullable(t.String()),
    Gross: t.Nullable(t.Integer()),
    Tax: t.Nullable(t.Integer()),
    Debit: t.Nullable(t.Integer()),
    Credit: t.Nullable(t.Integer()),
    Description: t.Nullable(t.String()),
    StockQty: t.Nullable(t.Integer()),
    StockCode: t.Nullable(t.String()),
    CostPrice: t.Nullable(t.Integer()),
    UnitPrice: t.Nullable(t.Integer()),
    Statement: t.Nullable(t.Integer()),
    JobCode: t.Nullable(t.String()),
    SaleUnit: t.Nullable(t.String()),
    Discount: t.Nullable(t.Integer()),
    Flags: t.Nullable(t.Integer()),
    OrderQty: t.Nullable(t.Integer()),
    BackorderQty: t.Nullable(t.Integer()),
    PrevShipQty: t.Nullable(t.Integer()),
    BaseCurrencyNet: t.Nullable(t.Integer()),
    SerialNumber: t.Nullable(t.String()),
    Period: t.Nullable(t.Integer()),
    TransactionType: t.Nullable(t.String()),
    SecurityLevel: t.Nullable(t.Integer()),
    RevalueQty: t.Nullable(t.Integer()),
    StockLocation: t.Nullable(t.String()),
    OrderStatus: t.Nullable(t.Boolean()),
    ExpensedTax: t.Nullable(t.Integer()),
    Date: t.Nullable(t.String()),
    MoreFlags: t.Nullable(t.Integer()),
    UserNum: t.Nullable(t.Integer()),
    UserText: t.Nullable(t.String()),
    TaggedText: t.Nullable(t.String()),
    NonInvRcvdNotInvoicedQty: t.Nullable(t.Integer()),
    Custom1: t.Nullable(t.String()),
    Custom2: t.Nullable(t.String()),
    OriginalUnitCost: t.Nullable(t.Integer()),
  },
  { additionalProperties: true },
);
