import { z } from "zod";

export const detailZod = z.object({
  SequenceNumber: z.number(),
  LastModifiedTime: z.string(),
  ParentSeq: z.number().optional().nullable(),
  Sort: z.number(),
  Account: z.string(),
  Dept: z.string(),
  PostedQty: z.number(),
  TaxCode: z.string(),
  Gross: z.number(),
  Tax: z.number(),
  Debit: z.number(),
  Credit: z.number(),
  Description: z.string(),
  StockQty: z.number(),
  StockCode: z.string(),
  CostPrice: z.number(),
  UnitPrice: z.number(),
  Statement: z.number(),
  JobCode: z.string(),
  SaleUnit: z.string(),
  Discount: z.number(),
  Flags: z.number(),
  OrderQty: z.number(),
  BackorderQty: z.number(),
  PrevShipQty: z.number(),
  BaseCurrencyNet: z.number(),
  SerialNumber: z.string(),
  Period: z.number(),
  TransactionType: z.string(),
  SecurityLevel: z.number(),
  RevalueQty: z.number(),
  StockLocation: z.string(),
  OrderStatus: z.boolean(),
  ExpensedTax: z.number(),
  Date: z.string(),
  MoreFlags: z.number(),
  UserNum: z.number(),
  UserText: z.string(),
  TaggedText: z.string(),
  NonInvRcvdNotInvoicedQty: z.number(),
  Custom1: z.string(),
  Custom2: z.string(),
  OriginalUnitCost: z.number(),
});

export type DetailZod = z.infer<typeof detailZod>;
