import { z } from "zod";

export const companyInformationZod = z.object({
  Name: z.string(),
  Address1: z.string(),
  Address2: z.string(),
  Address3: z.string(),
  Address4: z.string(),
  State: z.string(),
  PostCode: z.string(),
  Delivery1: z.string(),
  Delivery2: z.string(),
  Delivery3: z.string(),
  Delivery4: z.string(),
  DeliveryState: z.string(),
  DeliveryPostCode: z.string(),
  Phone: z.string(),
  Fax: z.string(),
  Email: z.string(),
  WebURL: z.string(),
  TaxName: z.string(),
  GstNum: z.string(),
  RegNum: z.string(),
  RemittanceMessage: z.string(),
  Have_Logo: z.boolean(),
  BaseCurrency: z.string(),
  Locale: z.string(),
  Version: z.string(),
  PeriodsInYear: z.number(),
  CurrentPer: z.number(),
  AgingCycle: z.number(),
  GstCycleEndDate: z.number(),
  GSTCycleMonths: z.number(),
  GstCycleNum: z.number(),
  GstIncomeInvoiceBasis: z.boolean(),
  CoRegName: z.string(),
  ExtendedJobCosting: z.boolean(),
  GSTExpensesInvoiceBasis: z.boolean(),
  GSTIncomeInvoiceBasis: z.boolean(),
  GSTProcessingSuppressed: z.boolean(),
  GSTGuideName: z.string(),
  GSTRegName: z.string(),
  LastAgedDebtors: z.string(),
  LastBackup: z.string(),
  LastStocktake: z.string(),
  LocaleFriendlyName: z.string(),
  LogFilePath: z.string(),
  Mobile: z.string(),
  MultiCurrencyEnabled: z.boolean(),
  NavigatorActive: z.boolean(),
  NetworkLatency: z.number(),
  PeriodNames: z.string(),
  StartupSequenceNumJob: z.number(),
});

export type CompanyInformationZod = z.infer<typeof companyInformationZod>;
