export default {
  "SequenceNumber": "integer",
  "LastModifiedTime": "date-time",
  "DevKey": "integer",
  "Key": "string",
  "Int1": "integer",
  "Int2": "integer",
  "Float1": "number",
  "Float2": "number",
  "Date1": "date",
  "Date2": "date",
  "Text1": "string",
  "Text2": "string",
  "Text": "string",
  "Int3": "integer",
  "Int4": "integer",
  "Float3": "number",
  "Float4": "number",
  "Date3": "date",
  "Date4": "date",
  "Text3": "string",
  "Text4": "string",
  "TaggedText": "string",
  "Colour": "integer"
};
