/**
 * MoneyWorks Transaction Type Definitions
 *
 * @moneyworks-entity Transaction
 * @moneyworks-table Transaction
 * @moneyworks-dsl PURE
 *
 * @ai-instruction USE ONLY MoneyWorks field names. NEVER translate to generic business terms.
 * @ai-forbidden invoice, payment, receipt (use Transaction type codes)
 * @ai-required SequenceNumber, Type, Status, TransDate, OurRef, NameCode
 *
 * Transaction is the main header entity for all financial transactions.
 * Detail entity contains the line items (Detail.ParentSeq -> Transaction.SequenceNumber)
 */

import type {
	MoneyWorksTransactionType,
	MoneyWorksTransactionStatus,
	MoneyWorksPaymentMethod,
} from "./enums";

/**
 * MoneyWorks Transaction field definitions
 * Source: moneyworks_appendix_transactions.html - Transactions table
 *
 * 65+ fields covering all transaction aspects:
 * - Identity: SequenceNumber, OurRef, TheirRef
 * - Classification: Type, Status, Colour
 * - Dates: TransDate, DueDate, EnterDate, DatePaid
 * - Financial: Gross, TaxAmount, AmtPaid, AmtWrittenOff
 * - Parties: NameCode, Contra
 * - Audit: EnteredBy, PostedBy, ApprovedBy1, ApprovedBy2
 */
export const MONEYWORKS_TRANSACTION_FIELDS = [
	// Identity fields
	"SequenceNumber",
	"OurRef",
	"TheirRef",
	"Type",
	"Status",

	// Date fields
	"TransDate",
	"DueDate",
	"EnterDate",
	"DatePaid",
	"LastModifiedTime",
	"TimePosted",
	"PromptPaymentDate",

	// Financial fields
	"Gross",
	"TaxAmount",
	"AmtPaid",
	"AmtWrittenOff",
	"PayAmount",
	"ExchangeRate",
	"PromptPaymentAmt",

	// Order/Shipping fields
	"OrderTotal",
	"OrderShipped",
	"OrderDeposit",
	"FreightAmount",
	"FreightCode",
	"FreightDetails",
	"OriginatingOrderSeq",

	// Party fields
	"NameCode",
	"Contra",
	"SalesPerson",
	"ToFrom",

	// Address fields
	"DeliveryAddress",
	"MailingAddress",

	// Description fields
	"Description",
	"Analysis",
	"Flag",

	// Control fields
	"Period",
	"Aging",
	"TaxCycle",
	"Colour",
	"PaymentMethod",
	"ProdPriceCode",
	"SecurityLevel",
	"Flags",

	// Boolean fields
	"Hold",
	"Recurring",
	"Printed",
	"Emailed",
	"Transferred",

	// Bank fields (for receipts)
	"BankJNSeq",
	"SpecialAccount",
	"SpecialBank",
	"SpecialBranch",

	// Approval fields
	"ApprovedBy1",
	"ApprovedBy2",

	// Audit fields
	"EnteredBy",
	"PostedBy",

	// User-defined fields
	"User1",
	"User2",
	"User3",
	"User4",
	"User5",
	"User6",
	"User7",
	"User8",
	"UserNum",
	"UserText",
	"TaggedText",
] as const;

/**
 * Type for transaction field names
 */
export type MoneyWorksTransactionField = (typeof MONEYWORKS_TRANSACTION_FIELDS)[number];

/**
 * MoneyWorks Transaction Entity
 *
 * CRITICAL: This is the header record. Line items are in the Detail table.
 * Relationship: Detail.ParentSeq -> Transaction.SequenceNumber
 *
 * @ai-critical NEVER translate MoneyWorks field names
 * @ai-context All monetary values are in document currency unless noted
 */
export interface MoneyWorksTransaction {
	// =========================================================================
	// IDENTITY FIELDS
	// =========================================================================

	/**
	 * Unique sequence number - PRIMARY KEY
	 * @moneyworks-field SequenceNumber
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "SequenceNumber", NEVER "id" or "transactionId"
	 * @ai-context Auto-generated by MoneyWorks, indexed
	 */
	SequenceNumber: number;

	/**
	 * Our reference number (invoice/receipt/cheque number)
	 * @moneyworks-field OurRef
	 * @moneyworks-type T(11)
	 * @ai-term ALWAYS use "OurRef", NEVER "invoiceNumber" or "reference"
	 * @ai-context CP=cheque#, CR=receipt#, DI=invoice#, CI=our PO#, JN=journal#
	 */
	OurRef: string;

	/**
	 * Their reference number
	 * @moneyworks-field TheirRef
	 * @moneyworks-type T(21)
	 * @ai-term ALWAYS use "TheirRef"
	 * @ai-context DI=customer order#, CI=supplier invoice#, CR=cheque#
	 */
	TheirRef?: string;

	/**
	 * Transaction type code
	 * @moneyworks-field Type
	 * @moneyworks-type T(3)
	 * @ai-term ALWAYS use "Type", NEVER "transactionType"
	 * @ai-context One of 17 MoneyWorksTransactionType values
	 */
	Type: MoneyWorksTransactionType | string;

	/**
	 * Transaction status
	 * @moneyworks-field Status
	 * @moneyworks-type T(1)
	 * @ai-term ALWAYS use "Status"
	 * @ai-context U=unposted (editable), P=posted (locked)
	 */
	Status: MoneyWorksTransactionStatus | string;

	// =========================================================================
	// DATE FIELDS
	// =========================================================================

	/**
	 * Transaction date
	 * @moneyworks-field TransDate
	 * @moneyworks-type D
	 * @ai-term ALWAYS use "TransDate", NEVER "date" or "transactionDate"
	 * @ai-context Financial reporting date
	 */
	TransDate: string;

	/**
	 * Due date for payment
	 * @moneyworks-field DueDate
	 * @moneyworks-type D
	 * @ai-context Calculated from TransDate + payment terms
	 */
	DueDate?: string;

	/**
	 * Date transaction was entered
	 * @moneyworks-field EnterDate
	 * @moneyworks-type D
	 * @ai-context System date when created, audit trail
	 */
	EnterDate?: string;

	/**
	 * Date last payment was made
	 * @moneyworks-field DatePaid
	 * @moneyworks-type D
	 * @ai-context For invoices, tracks payment activity
	 */
	DatePaid?: string;

	/**
	 * Last modification timestamp
	 * @moneyworks-field LastModifiedTime
	 * @moneyworks-type S
	 * @ai-context Read-only, set by MoneyWorks
	 */
	LastModifiedTime?: string;

	/**
	 * Posting timestamp
	 * @moneyworks-field TimePosted
	 * @moneyworks-type S
	 * @ai-context Precise timestamp when posted
	 */
	TimePosted?: string;

	/**
	 * Prompt payment discount deadline
	 * @moneyworks-field PromptPaymentDate
	 * @moneyworks-type D
	 * @ai-context Early payment discount expires on this date
	 */
	PromptPaymentDate?: string;

	// =========================================================================
	// FINANCIAL FIELDS
	// =========================================================================

	/**
	 * Gross value (total including tax)
	 * @moneyworks-field Gross
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "Gross", NEVER "total" or "amount"
	 */
	Gross?: number;

	/**
	 * Tax amount (GST/VAT)
	 * @moneyworks-field TaxAmount
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "TaxAmount", NEVER "gst" or "vat" or "tax"
	 */
	TaxAmount?: number;

	/**
	 * Amount paid against invoice
	 * @moneyworks-field AmtPaid
	 * @moneyworks-type N
	 * @ai-context For invoices, tracks partial payments
	 */
	AmtPaid?: number;

	/**
	 * Amount written off
	 * @moneyworks-field AmtWrittenOff
	 * @moneyworks-type N
	 * @ai-context Bad debt write-offs
	 */
	AmtWrittenOff?: number;

	/**
	 * Amount to pay in next payment run
	 * @moneyworks-field PayAmount
	 * @moneyworks-type N
	 * @ai-context For creditor invoice batch payments
	 */
	PayAmount?: number;

	/**
	 * Exchange rate (0 for base currency)
	 * @moneyworks-field ExchangeRate
	 * @moneyworks-type N
	 * @ai-context Multi-currency support
	 */
	ExchangeRate?: number;

	/**
	 * Prompt payment discount amount
	 * @moneyworks-field PromptPaymentAmt
	 * @moneyworks-type N
	 * @ai-context Early payment discount value
	 */
	PromptPaymentAmt?: number;

	// =========================================================================
	// ORDER/SHIPPING FIELDS
	// =========================================================================

	/**
	 * Total order value
	 * @moneyworks-field OrderTotal
	 * @moneyworks-type N
	 * @ai-context For order tracking
	 */
	OrderTotal?: number;

	/**
	 * Amount shipped
	 * @moneyworks-field OrderShipped
	 * @moneyworks-type N
	 */
	OrderShipped?: number;

	/**
	 * Deposit received on order
	 * @moneyworks-field OrderDeposit
	 * @moneyworks-type N
	 */
	OrderDeposit?: number;

	/**
	 * Freight amount
	 * @moneyworks-field FreightAmount
	 * @moneyworks-type N
	 */
	FreightAmount?: number;

	/**
	 * Freight code
	 * @moneyworks-field FreightCode
	 * @moneyworks-type T(15)
	 */
	FreightCode?: string;

	/**
	 * Freight details
	 * @moneyworks-field FreightDetails
	 * @moneyworks-type T(255)
	 */
	FreightDetails?: string;

	/**
	 * Sequence number of originating order
	 * @moneyworks-field OriginatingOrderSeq
	 * @moneyworks-type N
	 * @ai-context Links invoices back to orders
	 */
	OriginatingOrderSeq?: number;

	// =========================================================================
	// PARTY FIELDS
	// =========================================================================

	/**
	 * Customer or Supplier code
	 * @moneyworks-field NameCode
	 * @moneyworks-type T(11)
	 * @ai-term ALWAYS use "NameCode", NEVER "customer" or "supplier"
	 * @ai-context References Names.Code
	 */
	NameCode: string;

	/**
	 * Bank or control account code
	 * @moneyworks-field Contra
	 * @moneyworks-type T(7)
	 * @ai-term ALWAYS use "Contra"
	 * @ai-context CP/CR=bank account, CI/DI=control account
	 */
	Contra?: string;

	/**
	 * Salesperson code
	 * @moneyworks-field SalesPerson
	 * @moneyworks-type T(5)
	 */
	SalesPerson?: string;

	/**
	 * To/From field for payments
	 * @moneyworks-field ToFrom
	 * @moneyworks-type T(200)
	 * @ai-context Payment=To field, Receipt=From field
	 */
	ToFrom?: string;

	// =========================================================================
	// ADDRESS FIELDS
	// =========================================================================

	/**
	 * Delivery address override
	 * @moneyworks-field DeliveryAddress
	 * @moneyworks-type T(255)
	 * @ai-context Blank if using default from Name
	 */
	DeliveryAddress?: string;

	/**
	 * Mailing address override
	 * @moneyworks-field MailingAddress
	 * @moneyworks-type T(255)
	 */
	MailingAddress?: string;

	// =========================================================================
	// DESCRIPTION FIELDS
	// =========================================================================

	/**
	 * Transaction description
	 * @moneyworks-field Description
	 * @moneyworks-type T(1000)
	 * @ai-term ALWAYS use "Description"
	 */
	Description?: string;

	/**
	 * Analysis field
	 * @moneyworks-field Analysis
	 * @moneyworks-type T(9)
	 * @ai-context User-defined categorization
	 */
	Analysis?: string;

	/**
	 * Flag field
	 * @moneyworks-field Flag
	 * @moneyworks-type T(5)
	 * @ai-context User-defined text flag
	 */
	Flag?: string;

	// =========================================================================
	// CONTROL FIELDS
	// =========================================================================

	/**
	 * Accounting period
	 * @moneyworks-field Period
	 * @moneyworks-type N
	 * @ai-context Format: (100 * year_number + period_number)
	 */
	Period: number;

	/**
	 * Aging cycle
	 * @moneyworks-field Aging
	 * @moneyworks-type N
	 * @ai-context For receivables/payables aging
	 */
	Aging?: number;

	/**
	 * Tax cycle number
	 * @moneyworks-field TaxCycle
	 * @moneyworks-type N
	 * @ai-context 0 if not yet processed for tax
	 */
	TaxCycle?: number;

	/**
	 * Colour indicator
	 * @moneyworks-field Colour
	 * @moneyworks-type N
	 * @ai-term ALWAYS use "Colour" (British spelling)
	 * @ai-context 0-7 color index
	 */
	Colour?: number;

	/**
	 * Payment method
	 * @moneyworks-field PaymentMethod
	 * @moneyworks-type N
	 * @ai-context 0-7, see MoneyWorksPaymentMethod
	 */
	PaymentMethod?: MoneyWorksPaymentMethod | number;

	/**
	 * Product price code
	 * @moneyworks-field ProdPriceCode
	 * @moneyworks-type T(1)
	 * @ai-context A-F pricing matrix selection
	 */
	ProdPriceCode?: string;

	/**
	 * Security level
	 * @moneyworks-field SecurityLevel
	 * @moneyworks-type N
	 * @ai-context Access control level
	 */
	SecurityLevel?: number;

	/**
	 * Transaction flags (bitmask)
	 * @moneyworks-field Flags
	 * @moneyworks-type N
	 * @ai-context See MoneyWorksTransactionFlags
	 */
	Flags?: number;

	// =========================================================================
	// BOOLEAN FIELDS
	// =========================================================================

	/**
	 * Transaction on hold
	 * @moneyworks-field Hold
	 * @moneyworks-type B
	 */
	Hold?: boolean;

	/**
	 * Is recurring transaction template
	 * @moneyworks-field Recurring
	 * @moneyworks-type B
	 */
	Recurring?: boolean;

	/**
	 * Has been printed
	 * @moneyworks-field Printed
	 * @moneyworks-type N
	 * @ai-context 0=not printed, 1=printed
	 */
	Printed?: number;

	/**
	 * Has been emailed
	 * @moneyworks-field Emailed
	 * @moneyworks-type N
	 * @ai-context Non-zero if emailed
	 */
	Emailed?: number;

	/**
	 * Has been transferred (eInvoice)
	 * @moneyworks-field Transferred
	 * @moneyworks-type N
	 * @ai-context Non-zero if sent as eInvoice
	 */
	Transferred?: number;

	// =========================================================================
	// BANK FIELDS (for receipts)
	// =========================================================================

	/**
	 * Banking journal sequence number
	 * @moneyworks-field BankJNSeq
	 * @moneyworks-type N
	 * @ai-context References journal that banked the receipt
	 */
	BankJNSeq?: number;

	/**
	 * Cheque bank account
	 * @moneyworks-field SpecialAccount
	 * @moneyworks-type T
	 */
	SpecialAccount?: string;

	/**
	 * Cheque bank number
	 * @moneyworks-field SpecialBank
	 * @moneyworks-type T
	 */
	SpecialBank?: string;

	/**
	 * Cheque branch
	 * @moneyworks-field SpecialBranch
	 * @moneyworks-type T
	 */
	SpecialBranch?: string;

	// =========================================================================
	// APPROVAL FIELDS
	// =========================================================================

	/**
	 * First approver initials
	 * @moneyworks-field ApprovedBy1
	 * @moneyworks-type T(3)
	 * @ai-context Dual approval workflow
	 */
	ApprovedBy1?: string;

	/**
	 * Second approver initials
	 * @moneyworks-field ApprovedBy2
	 * @moneyworks-type T(3)
	 */
	ApprovedBy2?: string;

	// =========================================================================
	// AUDIT FIELDS
	// =========================================================================

	/**
	 * Entered by user initials
	 * @moneyworks-field EnteredBy
	 * @moneyworks-type A(3)
	 */
	EnteredBy?: string;

	/**
	 * Posted by user initials
	 * @moneyworks-field PostedBy
	 * @moneyworks-type A(3)
	 */
	PostedBy?: string;

	// =========================================================================
	// USER-DEFINED FIELDS
	// =========================================================================

	/** User-defined text 1 (255 chars) */
	User1?: string;
	/** User-defined text 2 (255 chars) */
	User2?: string;
	/** User-defined text 3 (255 chars) */
	User3?: string;
	/** User-defined text 4 (15 chars) */
	User4?: string;
	/** User-defined text 5 (15 chars) */
	User5?: string;
	/** User-defined text 6 (15 chars) */
	User6?: string;
	/** User-defined text 7 (15 chars) */
	User7?: string;
	/** User-defined text 8 (15 chars) */
	User8?: string;

	/** Scriptable number storage */
	UserNum?: number;
	/** Scriptable text storage (255 chars) */
	UserText?: string;
	/** Scriptable tag storage (255 chars) */
	TaggedText?: string;
}

/**
 * MoneyWorks Transaction creation input
 * Required fields for creating a new transaction
 *
 * @ai-instruction Type and Period are required. Other required fields depend on Type.
 */
export interface MoneyWorksTransactionCreateInput {
	/**
	 * Required: Transaction type
	 */
	Type: MoneyWorksTransactionType | string;

	/**
	 * Required: Accounting period
	 */
	Period: number;

	/**
	 * Transaction date (defaults to today)
	 */
	TransDate?: string;

	/**
	 * Reference number (auto-generated if not provided)
	 */
	OurRef?: string;

	/**
	 * Customer/Supplier code
	 */
	NameCode?: string;

	/**
	 * Description
	 */
	Description?: string;

	/**
	 * Bank/Control account
	 */
	Contra?: string;

	/**
	 * Gross amount
	 */
	Gross?: number;

	/**
	 * Other optional fields
	 */
	TheirRef?: string;
	DueDate?: string;
	Analysis?: string;
	Flag?: string;
	SalesPerson?: string;
	PaymentMethod?: MoneyWorksPaymentMethod | number;
	DeliveryAddress?: string;
	MailingAddress?: string;
	ToFrom?: string;
	FreightCode?: string;
	FreightAmount?: number;
	FreightDetails?: string;
	ProdPriceCode?: string;
	Hold?: boolean;
	Colour?: number;
	User1?: string;
	User2?: string;
	User3?: string;
	User4?: string;
	User5?: string;
	User6?: string;
	User7?: string;
	User8?: string;
	UserNum?: number;
	UserText?: string;
	TaggedText?: string;
}

/**
 * MoneyWorks Transaction update input
 * All fields optional - only include fields being changed
 *
 * @ai-instruction Note: Type, Period, Status cannot be changed after posting
 */
export interface MoneyWorksTransactionUpdateInput {
	OurRef?: string;
	TheirRef?: string;
	TransDate?: string;
	DueDate?: string;
	NameCode?: string;
	Description?: string;
	Contra?: string;
	Analysis?: string;
	Flag?: string;
	SalesPerson?: string;
	PaymentMethod?: MoneyWorksPaymentMethod | number;
	DeliveryAddress?: string;
	MailingAddress?: string;
	ToFrom?: string;
	FreightCode?: string;
	FreightAmount?: number;
	FreightDetails?: string;
	ProdPriceCode?: string;
	Hold?: boolean;
	Colour?: number;
	ApprovedBy1?: string;
	ApprovedBy2?: string;
	User1?: string;
	User2?: string;
	User3?: string;
	User4?: string;
	User5?: string;
	User6?: string;
	User7?: string;
	User8?: string;
	UserNum?: number;
	UserText?: string;
	TaggedText?: string;
}

/**
 * MoneyWorks Transaction filter for search/query operations
 *
 * @ai-instruction Use for querying transactions
 */
export interface MoneyWorksTransactionFilter {
	/**
	 * Filter by transaction type
	 */
	type?: MoneyWorksTransactionType | string;

	/**
	 * Filter by status
	 */
	status?: MoneyWorksTransactionStatus | string;

	/**
	 * Filter by customer/supplier code
	 */
	nameCode?: string;

	/**
	 * Filter by period
	 */
	period?: number;

	/**
	 * Filter by date range - start
	 */
	fromDate?: string;

	/**
	 * Filter by date range - end
	 */
	toDate?: string;

	/**
	 * Filter by our reference
	 */
	ourRef?: string;

	/**
	 * Filter by their reference
	 */
	theirRef?: string;

	/**
	 * Search text (searches Description, OurRef, TheirRef)
	 */
	searchText?: string;
}
