import { z } from "zod";

export const jobZod = z.object({
  SequenceNumber: z.number(),
  LastModifiedTime: z.date(),
  Code: z.string(),
  Description: z.string(),
  Client: z.string(),
  Comment: z.string(),
  StartDate: z.date(),
  Markup: z.number(),
  Quote: z.number(),
  Billed: z.number(),
  Status: z.string(),
  Flags: z.number(),
  Colour: z.number(),
  WIPAccount: z.string(),
  Category1: z.string(),
  Category2: z.string(),
  Category3: z.string(),
  Category4: z.string(),
  OrderNum: z.string(),
  Contact: z.string(),
  Phone: z.string(),
  EndDate: z.date(),
  Manager: z.string(),
  PercentComplete: z.number(),
  Variations: z.number(),
  RetentionsHeld: z.number(),
  RetentionsOwing: z.number(),
  ProductPricing: z.string(),
  RetainPercent: z.number(),
  UserNum: z.number(),
  UserText: z.string(),
  Project: z.string(),
  TargetDate: z.date(),
  Custom1: z.string(),
  Custom2: z.string(),
  Custom3: z.string(),
  Custom4: z.string(),
  TaggedText: z.string(),
  Custom5: z.string(),
  Custom6: z.string(),
  Custom7: z.string(),
  Custom8: z.string(),
});

export type JobZod = z.infer<typeof jobZod>;