import { t } from "elysia";
import { CompanyInformationOne } from "./eden/system/company-information";
import { AccountOne } from "./eden/tables/Account";
import { AutoSplitOne } from "./eden/tables/AutoSplit";
import { BankRecsOne } from "./eden/tables/BankRecs";
import { BuildOne } from "./eden/tables/Build";
import { DepartmentOne } from "./eden/tables/Department";
import { DetailOne } from "./eden/tables/Detail";
import { FilterOne } from "./eden/tables/Filter";
import { GeneralOne } from "./eden/tables/General";
import { JobOne } from "./eden/tables/Job";
import { JobSheetOne } from "./eden/tables/JobSheet";
import { LedgerOne } from "./eden/tables/Ledger";
import { LinkOne } from "./eden/tables/Link";
import { ListOne } from "./eden/tables/List";
import { LogOne } from "./eden/tables/Log";
import { LoginOne } from "./eden/tables/Login";
import { MemoOne } from "./eden/tables/Memo";
import { MessageOne } from "./eden/tables/Message";
import { NameOne } from "./eden/tables/Name";
import { OffLedgerOne } from "./eden/tables/OffLedger";
import { PaymentsOne } from "./eden/tables/Payments";
import { ProductOne } from "./eden/tables/Product";
import { StickiesOne } from "./eden/tables/Stickies";
import { TaxRateOne } from "./eden/tables/TaxRate";
import { TransactionOne } from "./eden/tables/Transaction";
import { UserOne } from "./eden/tables/User";
import { User2One } from "./eden/tables/User2";

export const accountObject = t.Partial(AccountOne);
export const autoSplitObject = t.Partial(AutoSplitOne);
export const bankRecsObject = t.Partial(BankRecsOne);
export const buildObject = t.Partial(BuildOne);
export const departmentObject = t.Partial(DepartmentOne);
export const detailObject = t.Partial(DetailOne);
export const filterObject = t.Partial(FilterOne);
export const generalObject = t.Partial(GeneralOne);
export const jobObject = t.Partial(JobOne);
export const jobSheetObject = t.Partial(JobSheetOne);
export const ledgerObject = t.Partial(LedgerOne);
export const linkObject = t.Partial(LinkOne);
export const listObject = t.Partial(ListOne);
export const logObject = t.Partial(LogOne);
export const loginObject = t.Partial(LoginOne);
export const memoObject = t.Partial(MemoOne);
export const messageObject = t.Partial(MessageOne);
export const nameObject = t.Partial(NameOne);
export const offLedgerObject = t.Partial(OffLedgerOne);
export const paymentsObject = t.Partial(PaymentsOne);
export const productObject = t.Partial(ProductOne);
export const stickiesObject = t.Partial(StickiesOne);
export const taxRateObject = t.Partial(TaxRateOne);
export const transactionObject = t.Partial(TransactionOne);
export const userObject = t.Partial(UserOne);
export const user2Object = t.Partial(User2One);
export const companyInformationObject = t.Partial(CompanyInformationOne);
