import { z } from "zod";
import { AccountFields } from "./interface/tables/account";
import { AutoSplitFields } from "./interface/tables/autosplit";
import { BankRecsFields } from "./interface/tables/bankrecs";
import { BuildFields } from "./interface/tables/build";
import { DepartmentFields } from "./interface/tables/department";
import { DetailFields } from "./interface/tables/detail";
import { FilterFields } from "./interface/tables/filter";
import { GeneralFields } from "./interface/tables/general";
import { JobFields } from "./interface/tables/job";
import { JobSheetFields } from "./interface/tables/jobsheet";
import { LedgerFields } from "./interface/tables/ledger";
import { LinkFields } from "./interface/tables/link";
import { ListsFields } from "./interface/tables/lists";
import { LogFields } from "./interface/tables/log";
import { LoginFields } from "./interface/tables/login";
import { MemoFields } from "./interface/tables/memo";
import { MessageFields } from "./interface/tables/message";
import { NameFields } from "./interface/tables/name";
import { OffLedgerFields } from "./interface/tables/offledger";
import { PaymentsFields } from "./interface/tables/payments";
import { ProductFields } from "./interface/tables/product";
import { StickiesFields } from "./interface/tables/stickies";
import { TaxRateFields } from "./interface/tables/taxrate";
import { TransactionFields } from "./interface/tables/transaction";
import { UserFields } from "./interface/tables/user";
import { User2Fields } from "./interface/tables/user2";

export const accountZodKeys = z.enum(AccountFields as [string]);
export const autoSplitZodKeys = z.enum(AutoSplitFields as [string]);
export const bankRecsZodKeys = z.enum(BankRecsFields as [string]);
export const buildZodKeys = z.enum(BuildFields as [string]);
export const departmentZodKeys = z.enum(DepartmentFields as [string]);
export const detailZodKeys = z.enum(DetailFields as [string]);
export const filterZodKeys = z.enum(FilterFields as [string]);
export const generalZodKeys = z.enum(GeneralFields as [string]);
export const jobZodKeys = z.enum(JobFields as [string]);
export const jobSheetZodKeys = z.enum(JobSheetFields as [string]);
export const ledgerZodKeys = z.enum(LedgerFields as [string]);
export const linkZodKeys = z.enum(LinkFields as [string]);
export const listsZodKeys = z.enum(ListsFields as [string]);
export const logZodKeys = z.enum(LogFields as [string]);
export const loginZodKeys = z.enum(LoginFields as [string]);
export const memoZodKeys = z.enum(MemoFields as [string]);
export const messageZodKeys = z.enum(MessageFields as [string]);
export const nameZodKeys = z.enum(NameFields as [string]);
export const offLedgerZodKeys = z.enum(OffLedgerFields as [string]);
export const paymentsZodKeys = z.enum(PaymentsFields as [string]);
export const productZodKeys = z.enum(ProductFields as [string]);
export const stickiesZodKeys = z.enum(StickiesFields as [string]);
export const taxRateZodKeys = z.enum(TaxRateFields as [string]);
export const transactionZodKeys = z.enum(TransactionFields as [string]);
export const userZodKeys = z.enum(UserFields as [string]);
export const user2ZodKeys = z.enum(User2Fields as [string]);
