import { z } from "zod";
import { AccountFields } from "./interface/account";
import { AutoSplitFields } from "./interface/auto-split";
import { BankRecsFields } from "./interface/bank-recs";
import { BuildFields } from "./interface/build";
import { DepartmentFields } from "./interface/department";
import { DetailFields } from "./interface/detail";
import { FilterFields } from "./interface/filter";
import { GeneralFields } from "./interface/general";
import { JobFields } from "./interface/job";
import { JobSheetFields } from "./interface/job-sheet";
import { LedgerFields } from "./interface/ledger";
import { LinkFields } from "./interface/link";
import { ListsFields } from "./interface/lists";
import { LogFields } from "./interface/log";
import { LoginFields } from "./interface/login";
import { MemoFields } from "./interface/memo";
import { MessageFields } from "./interface/message";
import { NameFields } from "./interface/name";
import { OffLedgerFields } from "./interface/off-ledger";
import { PaymentsFields } from "./interface/payments";
import { ProductFields } from "./interface/product";
import { StickiesFields } from "./interface/stickies";
import { TaxRateFields } from "./interface/tax-rate";
import { TransactionFields } from "./interface/transaction";
import { UserFields } from "./interface/user";
import { User2Fields } from "./interface/user2";

export const accountZodKeys = z.enum(AccountFields as [string]);
export const autoSplitZodKeys = z.enum(AutoSplitFields as [string]);
export const bankRecsZodKeys = z.enum(BankRecsFields as [string]);
export const buildZodKeys = z.enum(BuildFields as [string]);
export const departmentZodKeys = z.enum(DepartmentFields as [string]);
export const detailZodKeys = z.enum(DetailFields as [string]);
export const filterZodKeys = z.enum(FilterFields as [string]);
export const generalZodKeys = z.enum(GeneralFields as [string]);
export const jobZodKeys = z.enum(JobFields as [string]);
export const jobSheetZodKeys = z.enum(JobSheetFields as [string]);
export const ledgerZodKeys = z.enum(LedgerFields as [string]);
export const linkZodKeys = z.enum(LinkFields as [string]);
export const listsZodKeys = z.enum(ListsFields as [string]);
export const logZodKeys = z.enum(LogFields as [string]);
export const loginZodKeys = z.enum(LoginFields as [string]);
export const memoZodKeys = z.enum(MemoFields as [string]);
export const messageZodKeys = z.enum(MessageFields as [string]);
export const nameZodKeys = z.enum(NameFields as [string]);
export const offLedgerZodKeys = z.enum(OffLedgerFields as [string]);
export const paymentsZodKeys = z.enum(PaymentsFields as [string]);
export const productZodKeys = z.enum(ProductFields as [string]);
export const stickiesZodKeys = z.enum(StickiesFields as [string]);
export const taxRateZodKeys = z.enum(TaxRateFields as [string]);
export const transactionZodKeys = z.enum(TransactionFields as [string]);
export const userZodKeys = z.enum(UserFields as [string]);
export const user2ZodKeys = z.enum(User2Fields as [string]);
