import { t } from "elysia";

export const AssetOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.String(),
  Code: t.String(),
  Description: t.String(),
  Category: t.String(),
  SerialNum: t.Optional(t.Nullable(t.String())),
  Qty: t.Number(),
  ExpectedLife: t.Optional(t.Nullable(t.Number())),
  Cost: t.Number(),
  AccumDepreciation: t.Number(),
  AcquisitionDate: t.String(),
  LastDepreciatedDate: t.Optional(t.Nullable(t.String())),
  AcquisitionSeq: t.Optional(t.Nullable(t.Number())),
  DisposalSeq: t.Optional(t.Nullable(t.Number())),
  Location: t.Optional(t.Nullable(t.String())),
  Dept: t.Optional(t.Nullable(t.String())),
  PrivateUsePercent: t.Optional(t.Nullable(t.Number())),
  Status: t.String(),
  LastModifiedBy: t.Optional(t.Nullable(t.String())),
  LastRevaluedDate: t.Optional(t.Nullable(t.String())),
  ExpectedResidualValue: t.Optional(t.Nullable(t.Number())),
  RevalSurplusImpairAmt: t.Optional(t.Nullable(t.Number())),
  UserNum: t.Optional(t.Nullable(t.Number())),
  UserText: t.Optional(t.Nullable(t.String())),
  AccumDepnAdj: t.Optional(t.Nullable(t.Number())),
  BookValue: t.Number(),
  DisposalDate: t.Optional(t.Nullable(t.String())),
  GainLossOnDisposal: t.Optional(t.Nullable(t.Number())),
  Colour: t.Optional(t.Nullable(t.Number())),
  TaggedText: t.Optional(t.Nullable(t.String())),
  Type: t.String(),
  Rate: t.Number(),
  Comment: t.Optional(t.Nullable(t.String())),
  Custom1: t.Optional(t.Nullable(t.String())),
  Custom2: t.Optional(t.Nullable(t.String())),
  Custom3: t.Optional(t.Nullable(t.String())),
  Custom4: t.Optional(t.Nullable(t.String())),
});

export const AssetMany = t.Object({
  data: t.Array(t.Partial(AssetOne)),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  }),
});
