import { t } from 'elysia';
export const JobOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.Date(),
  Code: t.String(),
  Description: t.String(),
  Client: t.String(),
  Comment: t.Nullable(t.String()),
  StartDate: t.Nullable(t.Date()),
  Markup: t.Nullable(t.Number()),
  Quote: t.Nullable(t.Number()),
  Billed: t.Nullable(t.Number()),
  Status: t.Nullable(t.String()),
  Flags: t.Nullable(t.Number()),
  Colour: t.Nullable(t.Number()),
  WIPAccount: t.Nullable(t.String()),
  Category1: t.Nullable(t.String()),
  Category2: t.Nullable(t.String()),
  Category3: t.Nullable(t.String()),
  Category4: t.Nullable(t.String()),
  OrderNum: t.Nullable(t.String()),
  Contact: t.Nullable(t.String()),
  Phone: t.Nullable(t.String()),
  EndDate: t.Nullable(t.Date()),
  Manager: t.Nullable(t.String()),
  PercentComplete: t.Nullable(t.Number()),
  Variations: t.Nullable(t.Number()),
  RetentionsHeld: t.Nullable(t.Number()),
  RetentionsOwing: t.Nullable(t.Number()),
  ProductPricing: t.Nullable(t.String()),
  RetainPercent: t.Nullable(t.Number()),
  UserNum: t.Nullable(t.Number()),
  UserText: t.Nullable(t.String()),
  Project: t.Nullable(t.String()),
  TargetDate: t.Nullable(t.Date()),
  Custom1: t.Nullable(t.String()),
  Custom2: t.Nullable(t.String()),
  Custom3: t.Nullable(t.String()),
  Custom4: t.Nullable(t.String()),
  TaggedText: t.Nullable(t.String()),
  Custom5: t.Nullable(t.String()),
  Custom6: t.Nullable(t.String()),
  Custom7: t.Nullable(t.String()),
  Custom8: t.Nullable(t.String()),
});
export const JobMany = t.Object({
  data: t.Array(JobOne),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  })
});
