import { t } from "elysia";

export const JobOne = t.Object(
  {
    SequenceNumber: t.Integer(),
    LastModifiedTime: t.String(),
    Code: t.String(),
    Description: t.String(),
    Client: t.String(),
    Comment: t.Nullable(t.String()),
    StartDate: t.Nullable(t.Date()),
    Markup: t.Nullable(t.Integer()),
    Quote: t.Nullable(t.Integer()),
    Billed: t.Nullable(t.Integer()),
    Status: t.Nullable(t.String()),
    Flags: t.Nullable(t.Integer()),
    Colour: t.Nullable(t.Integer()),
    WIPAccount: t.Nullable(t.String()),
    Category1: t.Nullable(t.String()),
    Category2: t.Nullable(t.String()),
    Category3: t.Nullable(t.String()),
    Category4: t.Nullable(t.String()),
    OrderNum: t.Nullable(t.String()),
    Contact: t.Nullable(t.String()),
    Phone: t.Nullable(t.String()),
    EndDate: t.Nullable(t.Date()),
    Manager: t.Nullable(t.String()),
    PercentComplete: t.Nullable(t.Integer()),
    Variations: t.Nullable(t.Integer()),
    RetentionsHeld: t.Nullable(t.Integer()),
    RetentionsOwing: t.Nullable(t.Integer()),
    ProductPricing: t.Nullable(t.String()),
    RetainPercent: t.Nullable(t.Integer()),
    UserNum: t.Nullable(t.Integer()),
    UserText: t.Nullable(t.String()),
    Project: t.Nullable(t.String()),
    TargetDate: t.Nullable(t.Date()),
    Custom1: t.Nullable(t.String()),
    Custom2: t.Nullable(t.String()),
    Custom3: t.Nullable(t.String()),
    Custom4: t.Nullable(t.String()),
    TaggedText: t.Nullable(t.String()),
    Custom5: t.Nullable(t.String()),
    Custom6: t.Nullable(t.String()),
    Custom7: t.Nullable(t.String()),
    Custom8: t.Nullable(t.String()),
  },
  { additionalProperties: true },
);
