import { t } from "elysia";

export const JobSheetOne = t.Object(
  {
    SequenceNumber: t.Number(),
    LastModifiedTime: t.String(),
    Job: t.String(),
    Qty: t.Nullable(t.Number()),
    Resource: t.Nullable(t.String()),
    Date: t.Date(),
    CostCentre: t.Nullable(t.String()),
    Account: t.Nullable(t.String()),
    Period: t.Nullable(t.Number()),
    Units: t.Nullable(t.String()),
    CostPrice: t.Nullable(t.Number()),
    SellPrice: t.Nullable(t.Number()),
    Memo: t.Nullable(t.String()),
    DestTransSeq: t.Nullable(t.Number()),
    SourceTransSeq: t.Nullable(t.Number()),
    DateEntered: t.Nullable(t.Date()),
    Flags: t.Nullable(t.Number()),
    Colour: t.Nullable(t.Number()),
    Status: t.Nullable(t.String()),
    Type: t.Nullable(t.String()),
    Analysis: t.Nullable(t.String()),
    BillValue: t.Nullable(t.Number()),
    ActivityCode: t.Nullable(t.String()),
    Comments: t.Nullable(t.String()),
    Batch: t.Nullable(t.Number()),
    EnteredBy: t.Nullable(t.String()),
    SerialNumber: t.Nullable(t.String()),
    StockLocation: t.Nullable(t.String()),
    UserNum: t.Nullable(t.Number()),
    UserText: t.Nullable(t.String()),
    TaggedText: t.Nullable(t.String()),
    TimeProcessed: t.Nullable(t.Date()),
  },
  { additionalProperties: true },
);
