import { t } from "elysia";

export const MessageOne = t.Object(
  {
    SequenceNumber: t.Number(),
    LastModifiedTime: t.String(),
    StartDate: t.Nullable(t.Date()),
    EndDate: t.Nullable(t.Date()),
    NextDate: t.Nullable(t.Date()),
    Keep: t.Nullable(t.Boolean()),
    Ref: t.Nullable(t.Number()),
    LastDay: t.Nullable(t.Number()),
    NDaily: t.Nullable(t.Number()),
    NWeekly: t.Nullable(t.Number()),
    NMonthly: t.Nullable(t.Number()),
    Once: t.Nullable(t.Number()),
    XTimes: t.Nullable(t.Number()),
    Forever: t.Nullable(t.Number()),
    Day: t.Nullable(t.Number()),
    Type: t.Nullable(t.Number()),
    DayOfWeek: t.Nullable(t.Number()),
    N: t.Nullable(t.Number()),
    X: t.Nullable(t.Number()),
    AvoidWeekends: t.Nullable(t.Number()),
    Reverse: t.Nullable(t.Number()),
    kill_next_time: t.Nullable(t.Number()),
    Message: t.String(),
    User: t.Nullable(t.String()),
    UserNum: t.Nullable(t.Number()),
    UserText: t.Nullable(t.String()),
    TaggedText: t.Nullable(t.String()),
  },
  { additionalProperties: true },
);
