import { t } from 'elysia';
export const TaxRateOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.Date(),
  TaxCode: t.String(),
  PaidAccount: t.Nullable(t.String()),
  RecAccount: t.Nullable(t.String()),
  Rate1: t.Number(),
  Date: t.Nullable(t.Date()),
  Rate2: t.Nullable(t.Number()),
  Combine: t.Nullable(t.Number()),
  CombineRate1: t.Nullable(t.Number()),
  CombineRate2: t.Nullable(t.Number()),
  GSTReceived: t.Nullable(t.Number()),
  NetReceived: t.Nullable(t.Number()),
  GSTPaid: t.Nullable(t.Number()),
  NetPaid: t.Nullable(t.Number()),
  RateName: t.Nullable(t.String()),
  ReportCycleStart: t.Nullable(t.Number()),
  ReportCycleEnd: t.Nullable(t.Number()),
  ReportDate: t.Nullable(t.Date()),
  PSTReceived: t.Nullable(t.Number()),
  PSTPaid: t.Nullable(t.Number()),
  Type: t.Nullable(t.Number()),
  Combination: t.Nullable(t.String()),
  UserNum: t.Nullable(t.Number()),
  UserText: t.Nullable(t.String()),
  TaggedText: t.Nullable(t.String()),
  AliasCode: t.Nullable(t.String()),
  AliasCountry: t.Nullable(t.String()),
  ReversedRate1: t.Nullable(t.Number()),
  ReversedRate2: t.Nullable(t.Number()),
});
export const TaxRateMany = t.Object({
  data: t.Array(TaxRateOne),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  })
});
