import { z } from "zod";

export const accountSchema = z.object({
  SequenceNumber: z.number(),
  LastModifiedTime: z.date(),
  Code: z.string(),
  Type: z.string(),
  Group: z.string(),
  Category: z.string(),
  Description: z.string(),
  PandL: z.string(),
  TaxCode: z.string(),
  Flags: z.number(),
  System: z.string(),
  Created: z.date(),
  Category2: z.string(),
  Category3: z.string(),
  Category4: z.string(),
  AccountantCode: z.string(),
  Colour: z.number(),
  Currency: z.string(),
  SecurityLevel: z.number(),
  BankAccountNumber: z.string(),
  BalanceLimit: z.number(),
  ManualChequeNumber: z.string(),
  PrintedChequeNumber: z.string(),
  LastStatementImport: z.date(),
  Comments: z.string(),
  ManualChequeNumDigits: z.number(),
  PrintedChequeNumDigits: z.number(),
  UserNum: z.number(),
  UserText: z.string(),
  TaggedText: z.string(),
  FeedID: z.string(),
  Cashflow: z.string(),
  Cashforecast: z.string(),
  EBITDA: z.string(),
  ImportFormat: z.string(),
});

export type AccountSchema = z.infer<typeof accountSchema>;
