import type { RouteConfig } from "@react-router/dev/routes";
import { index, route } from "@react-router/dev/routes";

export default [
	index("routes/_index.tsx"),
	route("welcome", "routes/welcome.tsx"),
	route("sign-in", "routes/sign-in.tsx"),
	route("sign-up", "routes/sign-up.tsx"),
	route("dashboard", "routes/dashboard.tsx"),
	route("onboarding", "routes/onboarding.tsx"),
	route("connections", "routes/connections/index.tsx"),
	route("connections/new", "routes/connections/new.tsx"),
	route("connections/now", "routes/connections.now.tsx"),
	route("connections/now/new", "routes/connections.now.new.tsx"),
	route(
		"connections/now/select-files",
		"routes/connections.now.select-files.tsx",
	),
	route("connections/now/refresh", "routes/connections.now.refresh.tsx"),
	route("accounts", "routes/accounts.tsx"),
	route("accounts/:code", "routes/accounts.$code.tsx"),
	route("tax-rates", "routes/tax-rates.tsx"),
	route("tax-rates/:code", "routes/tax-rates.$code.tsx"),
	route("products", "routes/products.tsx"),
	route("products/:code", "routes/products.$code.tsx"),
	route("names", "routes/names.tsx"),
	route("company", "routes/company.tsx"),
	route("groups", "routes/groups.tsx"),
	route("tools/evaluate", "routes/tools.evaluate.tsx"),
	route("chat", "routes/chat.tsx"),
	route("chat/:sessionId", "routes/chat.$sessionId.tsx"),
	route("test-chat", "routes/test-chat.tsx"),
	route("settings", "routes/settings.tsx"),
	route("test-routes", "routes/test-routes.tsx"),
	route("test-auth", "routes/test-auth.tsx"),
	route("test-create-connection", "routes/test-create-connection.tsx"),
	route("test-connection-context", "routes/test-connection-context.tsx"),
	route("debug-connections-api", "routes/debug-connections-api.tsx"),
	route("api/connections", "routes/api.connections.tsx"),
	route("api/now-accounts", "routes/api.now-accounts.tsx"),
	route("api/debug/connections", "routes/api.debug.connections.tsx"),
	route("api/groups", "routes/api.groups.tsx"),
	route("api/groups/members", "routes/api.groups.members.tsx"),
	route("api/moneyworks", "routes/api.moneyworks.tsx"),
	route("api/moneyworks-test", "routes/api.moneyworks-test.tsx"),
	route("api/chat", "routes/api.chat.tsx"),
	route("api/chat/clear", "routes/api.chat.clear.tsx"),
	route("debug-auth", "routes/debug-auth.tsx"),
] satisfies RouteConfig;
