import { t } from "elysia";
export const AccountOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.Date(),
  Code: t.String(),
  Type: t.Optional(t.String()),
  Group: t.Optional(t.String()),
  Category: t.Optional(t.String()),
  Description: t.Optional(t.String()),
  PandL: t.Optional(t.String()),
  TaxCode: t.Optional(t.String()),
  Flags: t.Optional(t.Number()),
  System: t.Optional(t.String()),
  Created: t.Optional(t.Date()),
  Category2: t.Optional(t.String()),
  Category3: t.Optional(t.String()),
  Category4: t.Optional(t.String()),
  AccountantCode: t.Optional(t.String()),
  Colour: t.Optional(t.Number()),
  Currency: t.Optional(t.String()),
  SecurityLevel: t.Optional(t.Number()),
  BankAccountNumber: t.Optional(t.String()),
  BalanceLimit: t.Nullable(t.Optional(t.Number())),
  ManualChequeNumber: t.Optional(t.String()),
  PrintedChequeNumber: t.Optional(t.String()),
  LastStatementImport: t.Optional(t.Date()),
  Comments: t.Optional(t.String()),
  ManualChequeNumDigits: t.Nullable(t.Optional(t.Number())),
  PrintedChequeNumDigits: t.Nullable(t.Optional(t.Number())),
  UserNum: t.Optional(t.Number()),
  UserText: t.Optional(t.String()),
  TaggedText: t.Optional(t.String()),
  FeedID: t.Optional(t.String()),
  Cashflow: t.Optional(t.String()),
  Cashforecast: t.Optional(t.String()),
  EBITDA: t.Optional(t.String()),
  ImportFormat: t.Optional(t.String()),
});
export const AccountMany = t.Object({
  data: t.Array(AccountOne),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  }),
});
