import { t } from 'elysia';
export const DetailOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.Date(),
  ParentSeq: t.Number(),
  Sort: t.Optional(t.Number()),
  Account: t.String(),
  Dept: t.Optional(t.String()),
  PostedQty: t.Optional(t.Number()),
  TaxCode: t.Optional(t.String()),
  Gross: t.Optional(t.Number()),
  Tax: t.Optional(t.Number()),
  Debit: t.Optional(t.Number()),
  Credit: t.Optional(t.Number()),
  Description: t.Optional(t.String()),
  StockQty: t.Optional(t.Number()),
  StockCode: t.Optional(t.String()),
  CostPrice: t.Optional(t.Number()),
  UnitPrice: t.Optional(t.Number()),
  Statement: t.Optional(t.Number()),
  JobCode: t.Optional(t.String()),
  SaleUnit: t.Optional(t.String()),
  Discount: t.Optional(t.Number()),
  Flags: t.Optional(t.Number()),
  OrderQty: t.Optional(t.Number()),
  BackorderQty: t.Optional(t.Number()),
  PrevShipQty: t.Optional(t.Number()),
  BaseCurrencyNet: t.Optional(t.Number()),
  SerialNumber: t.Optional(t.String()),
  Period: t.Optional(t.Number()),
  TransactionType: t.Optional(t.String()),
  SecurityLevel: t.Optional(t.Number()),
  RevalueQty: t.Optional(t.Number()),
  StockLocation: t.Optional(t.String()),
  OrderStatus: t.Optional(t.Boolean()),
  ExpensedTax: t.Optional(t.Number()),
  Date: t.Optional(t.Date()),
  MoreFlags: t.Optional(t.Number()),
  UserNum: t.Optional(t.Number()),
  UserText: t.Optional(t.String()),
  TaggedText: t.Optional(t.String()),
  NonInvRcvdNotInvoicedQty: t.Optional(t.Number()),
  Custom1: t.Optional(t.String()),
  Custom2: t.Optional(t.String()),
  OriginalUnitCost: t.Optional(t.Number()),
});
export const DetailMany = t.Object({
  data: t.Array(DetailOne),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  })
});
