import { t } from 'elysia';
export const MessageOne = t.Object({
  SequenceNumber: t.Number(),
  LastModifiedTime: t.Date(),
  StartDate: t.Optional(t.Date()),
  EndDate: t.Optional(t.Date()),
  NextDate: t.Optional(t.Date()),
  Keep: t.Optional(t.Boolean()),
  Ref: t.Optional(t.Number()),
  LastDay: t.Optional(t.Number()),
  NDaily: t.Optional(t.Number()),
  NWeekly: t.Optional(t.Number()),
  NMonthly: t.Optional(t.Number()),
  Once: t.Optional(t.Number()),
  XTimes: t.Optional(t.Number()),
  Forever: t.Optional(t.Number()),
  Day: t.Optional(t.Number()),
  Type: t.Optional(t.Number()),
  DayOfWeek: t.Optional(t.Number()),
  N: t.Optional(t.Number()),
  X: t.Optional(t.Number()),
  AvoidWeekends: t.Optional(t.Number()),
  Reverse: t.Optional(t.Number()),
  kill_next_time: t.Optional(t.Number()),
  Message: t.String(),
  User: t.Optional(t.String()),
  UserNum: t.Optional(t.Number()),
  UserText: t.Optional(t.String()),
  TaggedText: t.Optional(t.String()),
});
export const MessageMany = t.Object({
  data: t.Array(MessageOne),
  pagination: t.Object({
    total: t.Number(),
    limit: t.Number(),
    offset: t.Number(),
    next: t.Number(),
    prev: t.Number(),
  })
});
